apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  selector:
    app: config-service
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: LoadBalancer
  loadBalancerIP: 35.189.212.195
#      nodePort: 31888
#  type: NodePort