apiVersion: v1
kind: Service
metadata:
  name: edge-service
spec:
  selector:
    app: edge-service
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
  type: LoadBalancer
  loadBalancerIP: 35.189.212.195