apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  selector:
    app: neo4j-service
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
  type: LoadBalancer
  loadBalancerIP: 35.189.212.195