apiVersion: v1
kind: Service
metadata:
  name: online-store-web
spec:
  selector:
    app: online-store-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8787
  type: LoadBalancer
  loadBalancerIP: 35.189.212.195