apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: catalog-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: catalog-service
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: catalog-service
        image: ycourtois/catalog-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value : docker