apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: discovery-service
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: discovery-service
        image: ycourtois/discovery-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value : docker
          - name: DOCKER_IP
            value: 35.189.212.195
        ports:
          - name: http
            containerPort: 8761