apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: mongo
        image: mongo:3.3
        ports:
          - name: http
            containerPort: 27017