apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
          - name: MYSQL_ROOT_PASSWORD
            value : dbpass
          - name: MYSQL_DATABASE
            value : dev
        ports:
          - name: http
            containerPort: 3306
#          resources:
#            limits:
#              cpu: 0.2
#              memory: "10Mi"