apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: online-store-web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: online-store-web
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: online-store-web
        image: ycourtois/online-store-web:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
          - name: DOCKER_IP
            value: 35.189.212.195
        ports:
          - name: http
            containerPort: 8787