apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: redis
        image: redis:3.0
        ports:
          - name: http
            containerPort: 6379