apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-service
        environment: dev
        context: event-sourcing
    spec:
      containers:
      - name: user-service
        image: ycourtois/user-service:latest
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
          - name: DOCKER_IP
            value: 35.189.212.195