apiVersion: v1
kind: Pod
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  containers:
    - name: account-service
      image: ycourtois/account-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker