apiVersion: v1
kind: Pod
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  containers:
    - name: catalog-service
      image: ycourtois/catalog-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker