apiVersion: v1
kind: Pod
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  containers:
    - name: config-service
      image: ycourtois/config-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker
      ports:
        - name: http
          containerPort: 8888