apiVersion: v1
kind: Pod
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  containers:
    - name: discovery-service
      image: ycourtois/discovery-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker
      ports:
        - name: http
          containerPort: 8761