apiVersion: v1
kind: Pod
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  containers:
    - name: edge-service
      image: ycourtois/edge-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker
        - name: DOCKER_IP
          value: 35.189.212.195
      ports:
        - name: http
          containerPort: 9999