apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: mysql:5.7
      env:
        - name: MYSQL_ROOT_PASSWORD
          value : dbpass
        - name: MYSQL_DATABASE
          value : dev
      ports:
        - name: http
          containerPort: 3306