apiVersion: v1
kind: Pod
metadata:
  name: neo4j
  labels:
    app: neo4j
spec:
  containers:
    - name: neo4j
      image: neo4j:2.3
      env:
        - name: NEO4J_AUTH
          value : none
      ports:
        - name: http
          containerPort: 7474