apiVersion: v1
kind: Pod
metadata:
  name: online-store-web
  labels:
    app: online-store-web
spec:
  containers:
    - name: online-store-web
      image: ycourtois/online-store-web:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker
        - name: DOCKER_IP
          value: 35.189.212.195
      ports:
        - name: http
          containerPort: 8787