apiVersion: v1
kind: Pod
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  containers:
    - name: order-service
      image: ycourtois/order-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker