apiVersion: v1
kind: Pod
metadata:
  name: shopping-cart-service
  labels:
    app: shopping-cart-service
spec:
  containers:
    - name: shopping-cart-service
      image: ycourtois/shopping-cart-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker