apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  containers:
    - name: user-service
      image: ycourtois/user-service:latest
      env:
        - name: SPRING_PROFILES_ACTIVE
          value : docker
      ports:
        - name: http
          containerPort: 8181